run:
  timeout: 1m

issues:
  exclude-dirs-use-default: true
  exclude-dirs:
    - example
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - goimports
    - goconst
    - gocritic
    - gochecknoinits
    - gochecknoglobals
    - gofmt
    - gosec
    - lll
    - misspell
    - nakedret
    - prealloc
    - rowserrcheck
    - stylecheck
    - unconvert
    - wastedassign
